title: Blog de Socram
description: Blog con experimentos personales de Socram
url: https://blog.orca.pet
author: Socram
image: /assets/socram.jpg
lang: es_ES
twitter:
    username: Socramite

remote_theme: lorepirri/cayman-blog

cayman-blog:
    date_format: "%d/%m/%Y"

defaults:
  - scope:
        path: ""
    values:
        excerpt_separator: "<!--more-->"
