title: Blog de Socram
description: Blog con experimentos personales de Socram
url: https://blog.orca.pet
author: Socram
lang: es_ES
twitter:
    username: Socramite

remote_theme: lorepirri/cayman-blog

defaults:
  - scope:
        path: ""
    values:
        excerpt_separator: "<!--more-->"
